"""
HELIOS OS + SEVRA AI
AI Metrics (Section 21)
"""

from prometheus_client import Counter, Histogram

class AIMetrics:
    def __init__(self):
        self.prediction_requests_total = Counter(
            'helios_ai_predictions_total',
            'Total predictions made',
            ['model_id']
        )
        self.prediction_latency_seconds = Histogram(
            'helios_ai_prediction_latency_seconds',
            'Time spent during ONNX inference',
            ['model_id']
        )
        self.anomalies_detected_total = Counter(
            'helios_ai_anomalies_total',
            'Total anomalies detected',
            ['metric']
        )
        self.alerts_generated_total = Counter(
            'helios_ai_alerts_total',
            'Total alerts generated by AI',
            ['severity']
        )

metrics = AIMetrics()
