"""
HELIOS OS + SEVRA AI
Alert Model
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import String, Text, Boolean, JSON, DateTime, Index
from sqlalchemy.orm import Mapped, mapped_column

from database.models.base import HeliosBase


class Alert(HeliosBase):
    """
    Clinical or system alerts generated by AI, Rules, or Devices.
    """
    __tablename__ = "alerts"

    client_event_id: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        index=True,
        nullable=False,
        comment="Original UUID assigned by the alerting engine. Idempotency key.",
    )

    patient_id: Mapped[Optional[str]] = mapped_column(
        String(36),
        index=True,
        nullable=True,
        comment="Reference to Patient.id (Null if system/device alert)",
    )

    alert_code: Mapped[str] = mapped_column(
        String(64),
        index=True,
        nullable=False,
        comment="Standardized alert code (e.g., 'MEWS_HIGH', 'SEPSIS_RISK', 'PROBE_OFF')",
    )

    severity: Mapped[str] = mapped_column(
        String(32),
        index=True,
        nullable=False,
        comment="CRITICAL, HIGH, MEDIUM, LOW, INFO",
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Human-readable alert description",
    )

    source_metric: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        comment="Metric that triggered the alert, if applicable",
    )

    is_acknowledged: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
        comment="Has a clinician acknowledged this alert?",
    )

    acknowledged_by: Mapped[Optional[str]] = mapped_column(
        String(128),
        nullable=True,
        comment="User ID of the clinician who acknowledged",
    )

    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp of acknowledgement",
    )

    resolved: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
        comment="Is the alert condition no longer active?",
    )
    
    resolved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    metadata_payload: Mapped[Optional[dict]] = mapped_column(
        JSON,
        nullable=True,
        comment="Clinical context, contributing factors, etc.",
    )

    __table_args__ = (
        Index("ix_alerts_patient_active", "patient_id", "resolved", "is_acknowledged"),
        Index("ix_alerts_sync_created", "sync_status", "created_at"),
    )
