title    SevraOS install medium (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-rt
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-rt.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
