"""initial_schema

Revision ID: aceb11873f1a
Revises: 
Create Date: 2026-06-26 14:46:55.331417

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aceb11873f1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Original UUID assigned by the alerting engine. Idempotency key.'),
    sa.Column('patient_id', sa.String(length=36), nullable=True, comment='Reference to Patient.id (Null if system/device alert)'),
    sa.Column('alert_code', sa.String(length=64), nullable=False, comment="Standardized alert code (e.g., 'MEWS_HIGH', 'SEPSIS_RISK', 'PROBE_OFF')"),
    sa.Column('severity', sa.String(length=32), nullable=False, comment='CRITICAL, HIGH, MEDIUM, LOW, INFO'),
    sa.Column('message', sa.Text(), nullable=False, comment='Human-readable alert description'),
    sa.Column('source_metric', sa.String(length=64), nullable=True, comment='Metric that triggered the alert, if applicable'),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False, comment='Has a clinician acknowledged this alert?'),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True, comment='User ID of the clinician who acknowledged'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of acknowledgement'),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='Is the alert condition no longer active?'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Clinical context, contributing factors, etc.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_code'), 'alerts', ['alert_code'], unique=False)
    op.create_index(op.f('ix_alerts_client_event_id'), 'alerts', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_deleted_at'), 'alerts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_acknowledged'), 'alerts', ['is_acknowledged'], unique=False)
    op.create_index('ix_alerts_patient_active', 'alerts', ['patient_id', 'resolved', 'is_acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_sync_created', 'alerts', ['sync_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_sync_status'), 'alerts', ['sync_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('client_event_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False, comment="E.g., 'USER_LOGIN', 'VIEW_PATIENT', 'ACKNOWLEDGE_ALERT'"),
    sa.Column('actor', sa.String(length=128), nullable=False, comment='User ID, Service Account, or System'),
    sa.Column('resource_id', sa.String(length=128), nullable=False, comment='The ID of the record that was accessed/modified'),
    sa.Column('details', sa.Text(), nullable=False, comment='Human readable summary'),
    sa.Column('context_payload', sa.JSON(), nullable=False, comment='Full context (IP address, user agent, previous state vs new state)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_action', 'audit_logs', ['actor', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_client_event_id'), 'audit_logs', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deleted_at'), 'audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_sync_status'), 'audit_logs', ['sync_status'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_id', 'created_at'], unique=False)
    op.create_index('ix_audit_sync_created', 'audit_logs', ['sync_status', 'created_at'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=128), nullable=False, comment='Unique device identifier (MAC address, serial number)'),
    sa.Column('device_type', sa.String(length=64), nullable=False, comment="Type of device (e.g., 'patient_monitor', 'ecg_patch', 'pulse_oximeter')"),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is the device currently allowed to connect?'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True, comment='Last time a heartbeat or payload was received'),
    sa.Column('assigned_patient_id', sa.String(length=36), nullable=True, comment='Currently assigned patient ID (UUID)'),
    sa.Column('location', sa.String(length=128), nullable=True, comment='Physical location if permanently mounted'),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Additional device-specific metadata'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_assigned_patient_id'), 'devices', ['assigned_patient_id'], unique=False)
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_devices_deleted_at'), 'devices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_is_active'), 'devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_devices_sync_status'), 'devices', ['sync_status'], unique=False)
    op.create_table('hospital_sync_queue',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Idempotency key. Usually maps to the triggering Vital or Alert event_id.'),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('sync_target', sa.String(length=64), nullable=False, comment="E.g., 'epic_fhir', 'cerner_mllp'"),
    sa.Column('payload', sa.JSON(), nullable=False, comment='The transformed data ready to be sent (e.g., FHIR JSON or HL7v2 base64)'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending, processing, success, failed, dead_letter'),
    sa.Column('send_attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_sync_queue_client_event_id'), 'hospital_sync_queue', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_hospital_sync_queue_created_at'), 'hospital_sync_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_sync_queue_deleted_at'), 'hospital_sync_queue', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hospital_sync_queue_patient_id'), 'hospital_sync_queue', ['patient_id'], unique=False)
    op.create_index(op.f('ix_hospital_sync_queue_status'), 'hospital_sync_queue', ['status'], unique=False)
    op.create_index(op.f('ix_hospital_sync_queue_sync_status'), 'hospital_sync_queue', ['sync_status'], unique=False)
    op.create_index(op.f('ix_hospital_sync_queue_sync_target'), 'hospital_sync_queue', ['sync_target'], unique=False)
    op.create_index('ix_hospital_sync_sync_created', 'hospital_sync_queue', ['sync_status', 'created_at'], unique=False)
    op.create_index('ix_hospital_sync_target_status', 'hospital_sync_queue', ['sync_target', 'status', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Idempotency key for the notification attempt'),
    sa.Column('recipient_id', sa.String(length=128), nullable=False, comment='User ID, phone number, or pager ID'),
    sa.Column('channel', sa.String(length=32), nullable=False, comment='SMS, PUSH, PAGER, EMAIL'),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending, sent, failed, delivered, read'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Gateway provider response, exact payload sent, etc.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_client_event_id'), 'notifications', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_status', 'notifications', ['recipient_id', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_sync_created', 'notifications', ['sync_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_sync_status'), 'notifications', ['sync_status'], unique=False)
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=64), nullable=False, comment='Medical Record Number (unique per facility)'),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True, comment='Ward/Bed/Room location'),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Extensible patient metadata (allergies, primary care physician, etc.)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_deleted_at'), 'patients', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_patients_location'), 'patients', ['location'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_index(op.f('ix_patients_sync_status'), 'patients', ['sync_status'], unique=False)
    op.create_table('predictions',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Idempotency key from AI Engine'),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False, comment='Identifier for the exact AI model version used'),
    sa.Column('prediction_type', sa.String(length=64), nullable=False, comment="Type of prediction (e.g., 'sepsis_risk_6h', 'mortality_risk')"),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Normalized score, usually 0.0 to 1.0 or 0 to 100'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Model confidence in the prediction (0.0 to 1.0)'),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Feature importance, contributing factors, SHAP values'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_client_event_id'), 'predictions', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_deleted_at'), 'predictions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_predictions_patient_id'), 'predictions', ['patient_id'], unique=False)
    op.create_index('ix_predictions_patient_type', 'predictions', ['patient_id', 'prediction_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_index('ix_predictions_sync_created', 'predictions', ['sync_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_sync_status'), 'predictions', ['sync_status'], unique=False)
    op.create_table('rejected_readings',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Idempotency key from Collector'),
    sa.Column('source_device', sa.String(length=128), nullable=False),
    sa.Column('rejection_stage', sa.String(length=64), nullable=False, comment="e.g., 'mdil_parse', 'validation_structural', 'validation_clinical', 'normalization'"),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False, comment='The actual data that failed'),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejected_device_stage', 'rejected_readings', ['source_device', 'rejection_stage'], unique=False)
    op.create_index(op.f('ix_rejected_readings_client_event_id'), 'rejected_readings', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_rejected_readings_created_at'), 'rejected_readings', ['created_at'], unique=False)
    op.create_index(op.f('ix_rejected_readings_deleted_at'), 'rejected_readings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rejected_readings_rejection_stage'), 'rejected_readings', ['rejection_stage'], unique=False)
    op.create_index(op.f('ix_rejected_readings_source_device'), 'rejected_readings', ['source_device'], unique=False)
    op.create_index(op.f('ix_rejected_readings_sync_status'), 'rejected_readings', ['sync_status'], unique=False)
    op.create_index('ix_rejected_sync_created', 'rejected_readings', ['sync_status', 'created_at'], unique=False)
    op.create_table('system_events',
    sa.Column('client_event_id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False, comment="E.g., 'mdil', 'database_service', 'sync_engine'"),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment="E.g., 'STARTUP', 'SHUTDOWN', 'SYNC_ERROR', 'HEARTBEAT_LOST'"),
    sa.Column('severity', sa.String(length=32), nullable=False, comment='INFO, WARN, ERROR, CRITICAL'),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False, comment='Stack traces, configuration values, host metrics'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_component_type', 'system_events', ['component', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_events_client_event_id'), 'system_events', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_system_events_component'), 'system_events', ['component'], unique=False)
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_deleted_at'), 'system_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_severity'), 'system_events', ['severity'], unique=False)
    op.create_index(op.f('ix_system_events_sync_status'), 'system_events', ['sync_status'], unique=False)
    op.create_index('ix_system_sync_created', 'system_events', ['sync_status', 'created_at'], unique=False)
    op.create_table('vitals',
    sa.Column('client_event_id', sa.String(length=36), nullable=False, comment='Original UUID assigned by Collector. The idempotency key.'),
    sa.Column('patient_id', sa.String(length=36), nullable=False, comment='Reference to Patient.id'),
    sa.Column('metric', sa.String(length=64), nullable=False, comment="Standardized metric name (e.g., 'heart_rate', 'spo2')"),
    sa.Column('value', sa.Float(), nullable=False, comment='Numerical value of the observation'),
    sa.Column('unit', sa.String(length=32), nullable=False, comment='UCUM standard unit'),
    sa.Column('loinc', sa.String(length=32), nullable=False, comment='LOINC code for interoperability'),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False, comment='Time the reading was actually captured by the device (UTC)'),
    sa.Column('source_device', sa.String(length=128), nullable=False, comment='Device ID that generated this vital'),
    sa.Column('flagged', sa.Boolean(), nullable=False, comment='Flagged by validation as unusual/outlier'),
    sa.Column('metadata_payload', sa.JSON(), nullable=True, comment='Extra info: signal quality, battery level, etc.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Immutable creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.Column('created_by', sa.String(length=128), nullable=False, comment='Actor who created this record'),
    sa.Column('updated_by', sa.String(length=128), nullable=False, comment='Actor who last modified this record'),
    sa.Column('sync_status', sa.String(length=16), nullable=False, comment='Replication state: pending | synced | error'),
    sa.Column('sync_attempts', sa.Integer(), nullable=False, comment='Number of sync attempts'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Last sync attempt timestamp'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_client_event_id'), 'vitals', ['client_event_id'], unique=True)
    op.create_index(op.f('ix_vitals_created_at'), 'vitals', ['created_at'], unique=False)
    op.create_index(op.f('ix_vitals_deleted_at'), 'vitals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vitals_flagged'), 'vitals', ['flagged'], unique=False)
    op.create_index(op.f('ix_vitals_loinc'), 'vitals', ['loinc'], unique=False)
    op.create_index(op.f('ix_vitals_metric'), 'vitals', ['metric'], unique=False)
    op.create_index('ix_vitals_patient_captured', 'vitals', ['patient_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_vitals_patient_id'), 'vitals', ['patient_id'], unique=False)
    op.create_index('ix_vitals_patient_metric_captured', 'vitals', ['patient_id', 'metric', 'captured_at'], unique=False)
    op.create_index(op.f('ix_vitals_source_device'), 'vitals', ['source_device'], unique=False)
    op.create_index(op.f('ix_vitals_sync_status'), 'vitals', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitals_sync_status'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_source_device'), table_name='vitals')
    op.drop_index('ix_vitals_patient_metric_captured', table_name='vitals')
    op.drop_index(op.f('ix_vitals_patient_id'), table_name='vitals')
    op.drop_index('ix_vitals_patient_captured', table_name='vitals')
    op.drop_index(op.f('ix_vitals_metric'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_loinc'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_flagged'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_deleted_at'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_created_at'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_client_event_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index('ix_system_sync_created', table_name='system_events')
    op.drop_index(op.f('ix_system_events_sync_status'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_severity'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_deleted_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_component'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_client_event_id'), table_name='system_events')
    op.drop_index('ix_system_component_type', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_rejected_sync_created', table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_sync_status'), table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_source_device'), table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_rejection_stage'), table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_deleted_at'), table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_created_at'), table_name='rejected_readings')
    op.drop_index(op.f('ix_rejected_readings_client_event_id'), table_name='rejected_readings')
    op.drop_index('ix_rejected_device_stage', table_name='rejected_readings')
    op.drop_table('rejected_readings')
    op.drop_index(op.f('ix_predictions_sync_status'), table_name='predictions')
    op.drop_index('ix_predictions_sync_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_index('ix_predictions_patient_type', table_name='predictions')
    op.drop_index(op.f('ix_predictions_patient_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_deleted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_client_event_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_patients_sync_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_location'), table_name='patients')
    op.drop_index(op.f('ix_patients_deleted_at'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_notifications_sync_status'), table_name='notifications')
    op.drop_index('ix_notifications_sync_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_client_event_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_hospital_sync_target_status', table_name='hospital_sync_queue')
    op.drop_index('ix_hospital_sync_sync_created', table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_sync_target'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_sync_status'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_status'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_patient_id'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_deleted_at'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_created_at'), table_name='hospital_sync_queue')
    op.drop_index(op.f('ix_hospital_sync_queue_client_event_id'), table_name='hospital_sync_queue')
    op.drop_table('hospital_sync_queue')
    op.drop_index(op.f('ix_devices_sync_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_active'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_deleted_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_assigned_patient_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_sync_created', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sync_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deleted_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_client_event_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_sync_status'), table_name='alerts')
    op.drop_index('ix_alerts_sync_created', table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_index('ix_alerts_patient_active', table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_acknowledged'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_deleted_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_client_event_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_code'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
